export enum AT {
    ADD_SCORE = 'ADD_SCORE',
    
    USER_LOGIN = 'USER_LOGIN',
    USER_LOGOUT = 'USER_LOGOUT',

    GET_USERS_ASYNC = 'GET_USERS_ASYNC',
    GET_USERS_FULFILLED = 'GET_USERS_FULFILLED',
    GET_USERS_REJECTED = 'GET_USERS_REJECTED'
}

export default AT